### ISSUE TITLE
BUG: 当前计算方式容量不可靠。

### ISSUE THREAD

**Issue by SmallTianTian** [parvin92/flycache#1]
https://github.com/parvin92/flycache/blob/c13e1b6a92129b086dc5e8823e437fde3f860a54/lru/lru.go#L72

只有在新增的时候考虑过 `usedBytes`，在移除的时候，并没有回收这部分容量。

**Comment by parvinshi** [comment]
> https://github.com/parvin92/flycache/blob/c13e1b6a92129b086dc5e8823e437fde3f860a54/lru/lru.go#L72
> 
> 只有在新增的时候考虑过 `usedBytes`，在移除的时候，并没有回收这部分容量。

嗯，加了个UpdateUsedBytes方法，在新增和删除的时候都更新下已使用的字节数。
